version: '3.9'

services:
  postgres:
    container_name: blazor_postgres_container
    image: postgres:bullseye
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-template}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-template}
      POSTGRES_DB: ${POSTGRES_DATABASE:-template}
    ports:
      - "35432:5432"
    restart: always

volumes:
  postgres: {}
